### ISSUE TITLE
stranger-things.php

### ISSUE THREAD

**Issue by a-bikombe** [a-bikombe/aribikombe#11]
**To-Do List**

- [x] character rank
- [ ] thoughts (as I marathon)
- [x] season 4 character info
- [ ] any extra info from vol 2

**Comment by a-bikombe** [comment]
ST1-3
Blink once for yes, twice for no

**Comment by a-bikombe** [comment]
#Episode Six

This one\'s kind of boring too, but I was a fan of El robbing the grocery store. It\'s so funny how she doesn\'t know to hide her powers.

-

**Comment by a-bikombe** [comment]
- [ ] Season 4 character info

**Comment by a-bikombe** [comment]
hello

**Comment by a-bikombe** [comment]
**Season 2, Chapter Five**



-

**Comment by a-bikombe** [comment]
**Season 2, Chapter Six**



-

**Comment by a-bikombe** [comment]
**Season 2, Chapter Seven**



-

**Comment by a-bikombe** [comment]
**Season 2, Chapter Eight**



- We can\'t just sit here while those <em>things</em> are loose
- It\'s like a play on words—" "Okay

**Comment by a-bikombe** [comment]
**Season 2, Chapter Nine**

Lucas\'s scream

- Protecting her… PROTECTING HER?
- Maybe if we set this on <em>fire</em>—" "Yeah, <em>that\'s</em> a no
- Nancy?
- *Screaming* "...I\'m okay"

**Comment by a-bikombe** [comment]
march 21 1986

**Comment by a-bikombe** [comment]
_Mike_ + Nancy downstairs + Pop Tarts
37:28 smile i hate myself + Dustin/Mike/Eddie in general
44:00 why is he pretty and expressive
57:48 WE GOT THE POUT

**Comment by a-bikombe** [comment]
**Ch 2**

- Visor city
- "Twig"

**Comment by a-bikombe** [comment]
ch 3

pouty looking at the police station desk lady

**Comment by a-bikombe** [comment]
### episode rank
1. Chapter Four: Dear Billy
2. Chapter One: The Hellfire Club
3. Chapter Three: The Monster And The Superhero
4. Chapter Seven: The Massacre at Hawkins Lab
5. Chapter Two: Vecna’s Curse
6. Chapter Six: The Dive
7. Chapter Five: The Nina Project

**Comment by a-bikombe** [comment]
### Ch 4

**Comment by a-bikombe** [comment]
### Chapter Five: The Nina Project

**Comment by a-bikombe** [comment]
### Chapter Six: The Dive

**Comment by a-bikombe** [comment]
### Chapter Seven: The Massacre at Hawkins Lab

**Comment by a-bikombe** [comment]
## Eddie

- Sweet baby

**Comment by a-bikombe** [comment]
Chapter One: 3/21
Chapter Two: 3/22
Chapter Three: 3/23
Chapter Four: 3/24
Chapter Five: 3/25
Chapter Six: 3/
Chapter Seven: 3/
Chapter Eight: 3/
Chapter Nine: 3/
